server:
    port: 9999

spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql:///film?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        port: 6379
        host: localhost
    servlet:
        multipart:
            max-file-size: 5MB

logging:
    level:
        com.design.filmr: debug

mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: deleted
            logic-not-delete-value: 0
            logic-delete-value: 1
knife4j:
    enable: true
    openapi:
        title: 影视推荐交流观影平台
        description: "记录本次项目的所有接口"
        email: xiaoymin@foxmail.com
        concat: 东方幻想乡
        url: https://docs.xiaominfo.com
        version: v4.0
        license: Apache 2.0
        license-url: https://stackoverflow.com/
        terms-of-service-url: https://stackoverflow.com/
        group:
            test1:
                group-name: 分组名称
                api-rule: package
                api-rule-resources:
                    - com.design.filmr
